### Site info:
title: Kyo's Blog
tagline: MBA Data Scientist in FMCG industry
author: Kyo
email: kyoichiro.harada@bath.edu
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
baseurl: "Kyo.github.io" # the subpath of your site, e.g. /blog/
url: "https://kyo1988.github.io/Kyo.github.io/" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: kyoHarada
github_username:  kyo1988
disqus_shortname: kyo
favicon:     "/images/IMG_0168.ico" #favicon.ico"
aboutme: Hi, this is Kyo. I made this site using the Freshman21 theme. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://res.cloudinary.com/djiyxp5ax/image/upload/v1621667206/IMG_0082_txvfj3.jpg # your photo.
google_analytics_key: G-89K1E4WTNW # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Kyo's Blog
        href: https://kyo1988.github.io/Kyo.github.io/
        title: Kyo's Blog

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
