### Site info:
title: Kyo's Blog
tagline: MBA | Brand Manager | Data Scientist
author: Kyo
email: kh685mba@gmail.com
description: "Blog by Kyo who am a freelancing Data Scientist and Consultant"
keywords: "Brand Manager, Freelancer, Data Scientist, Consultant"
baseurl: "/Kyo.github.io" # the subpath of your site, e.g. /blog/
url: "https://kyo1988.github.io/Kyo.github.io/" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: kyoHarada
github_username:  kyo1988
disqus_shortname: kyo
favicon:     "/images/IMG_0168.ico" #favicon.ico"
aboutme: Hi, this is Kyo, who am  a freelancing data scientist and consultant while working in a cosmetic firm as a brand manager. # these are shown on aboutme-sidebar.
aboutme_photo: https://res.cloudinary.com/djiyxp5ax/image/upload/v1621667206/IMG_0082_txvfj3.jpg # your photo.
google_analytics_key: UA-196500796-1 # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Recent_Posts: "Recent Posts"
      Categories: "Categories"
      Tags: "Tags"
      Archives: "Archives"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
###      Subscribe: "Subscribe"
      Review: "Review"
      Visualization: "Visualization"
      Marketing: "Marketing"

###      Copyright_Notice: "Copyright Notice"
###      Blogroll: "Blogroll"
###      Guestbook: "Guestbook"

### your Blogroll info, only name can shown on the page.

# Blogroll:
#       - name: Kyo's Blog
#         href: https://kyo1988.github.io/Kyo.github.io/
#         title: Kyo's Blog

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts

paginate: 3
excerpt_separator: <!-- more -->